[project]
name = "beangulp-hooks"
version = "0.1.0"
description = "Hooks for the beangulp importer."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beancount>=3.1.0",
    "beangulp>=0.2.0",
    "numpy>=2.2.3",
    "scikit-learn>=1.6.1",
]
